# Nutrition Tracking

1. Program allows users to enter the name of the food and brand owner and get nutrients on the food.
2. The food and brand name must be written exactly as entered in food and branded_food Excel workbooks.
3. In order for the program to work, the user needs to download the latest zipped folder as a CSV file from the Branded Data Type on the FoodData Central Website 
https://fdc.nal.usda.gov/download-datasets.html
4. When running a report, some foods will not record any nutrients or might record very few nutrients. The lack of nutrients is due to the brand company reporting few to no nutrients. No nutrients does not mean a food does not have nutrients.
5. Food's nutrients are recorded for 100g of food, so not the exact same as what label says.
6. Manufactures have leway when putting nutritional information on the product label. Often have more than what is listed, such as more calories, by up to 10%.

# Load the modules

In [3]:
import pandas as pd

# Load the Files

In [4]:
df_food = pd.read_csv('food.csv')
df_food["description"] = df_food["description"].astype(str)

df_branded_food = pd.read_csv('branded_food.csv', low_memory=False)

In [5]:
df_food_nutrients = pd.read_csv('food_nutrient.csv')

In [8]:
df_nutrients_2 = df_food_nutrients

In [7]:
df_food_nutrients = df_nutrients_2

# Locate Food and Brand Owner

In [9]:
# asks user for description of food and converts it to upper case
user_food_description = input("Enter the exact description of the food: ")
user_food_description = user_food_description.upper()
print("Description: " + user_food_description)
print()

# splits the food description provided by user into a list and converts all food descriptions to list
list_user_food_description = user_food_description.split()
list_all_food_descriptions = df_food["description"].tolist()

# loops through list description provided by user and compares it with the list of all food descriptions
# if a word provided by the user is in the list of all food descriptions, append to new list.
# get all columns of foods dataframe where description is in the list of descriptions
# assigns the list of descriptions to the list of all food descriptions and repeats the process,
# until all words from the user description have been looked at
list_descriptions = []
for i in range(0, len(list_user_food_description)):
    for j in range(0, len(list_all_food_descriptions)):
        if list_user_food_description[i] in list_all_food_descriptions[j]:
            list_descriptions.append(list_all_food_descriptions[j])
    df_select_foods = df_food[df_food["description"].isin(list_descriptions)]
    list_all_food_descriptions = list_descriptions
    list_descriptions = []

# converts ids of the dataframe select foods to a list.
# Checks the dateframe of branded food and gets the rows where fdc_id is in the list of fdc_ids.
# Creates a new dataframe.
list_fdc_ids = df_select_foods["fdc_id"].tolist()
df_select_branded_food = df_branded_food[df_branded_food["fdc_id"].isin(list_fdc_ids)]

Enter the exact description of the food: 100% whole grain
Description: 100% WHOLE GRAIN

In [10]:
# converts the brand owners of the select branded food to a list.
list_brand_owners = df_select_branded_food["brand_owner"].tolist()

# get unique brand owners and sort the list
unique_list = []
for x in list_brand_owners:
    if x not in unique_list:
        unique_list.append(x)
unique_list = sorted(unique_list)

# print out numbered list of unique brands   
for i in range(0, len(unique_list)):
    print(str(i+1) + ") " + unique_list[i])
print()

# ask user which number the brand owner of the food is
number = int(input("Which number is your brand?: "))
brand = unique_list[number-1]

1) Adams Global Communications Inc.
2) Ahold USA, Inc.
3) Ahold Usa, Inc.
4) Aldi Inc.
5) Aldi-Benner Company
6) Alpha Baking Co., Inc.
7) American Italian Pasta Company
8) Arco Distributors, Inc.
9) Associated Wholesale Grocers, Inc.
10) Atoria's Baking Company
11) Avb Corp.
12) BIMBO BAKERIES USA, INC.
13) BUTTERNUT
14) Baby Time International Inc.
15) Baker Mills
16) Bay Valley Foods, LLC
17) Bi-Lo Inc.
18) Big Y Foods, Inc.
19) Bimbo Bakeries USA, Inc.
20) Birkett Mills
21) Bob's Red Mill Natural Foods, Inc.
22) Borden Inc./dairy & Service Div.
23) Bruno's Supermarkets, Inc.
24) CALIFORNIA LAVASH
25) CLEARLY
26) CLOVER VALLEY
27) CVS Pharmacy, Inc.
28) Canyon Bakehouse LLC
29) Catallia Mexican Foods LLC
30) Community Grains
31) Community Grains
32) Conagra Foods-Snack Foods Group
33) Continental Mills, Inc.
34) Del Monte Foods Inc.
35) Delhaize America, Inc.
36) FIRST STREET
37) FOOD LION
38) Flowers Foods, Inc.
39) Food For Life Baking Co Inc
40) Fox Point Sportswear, Inc.
41) Frito-Lay Company
42) GOOD & SMART
43) GOURMET NUT
44) GS1 Ireland
45) Glencourt Inc.
46) Global Juices and Fruits, LLC
47) Gold Medal Bakery Inc.
48) Grain Millers, Inc.
49) HEARTLAND GRAINS
50) HOMELAND
51) Hannaford Bros. Co.
52) Harris-Teeter Inc.
53) Homeland Stores, Inc.
54) Homestat Farm, Ltd.
55) Hometown BCN Inc.
56) Hot On The Spot
57) Hy-Vee, Inc.
58) Iga, Inc.
59) Ingles Markets Inc.
60) JOVIAL
61) KASHI GO
62) KIND Inc.
63) Kraft Heinz Foods Company
64) Lantev Distributing Inc.
65) Lepage Bakeries, Inc.
66) Lewis Bakeries Inc.
67) Lunds Inc
68) MOM Brands Company
69) Maplehurst Bakeries, LLC
70) Meijer, Inc.
71) Nabisco Biscuit Company
72) Nash Finch Company
73) New World Pasta Company
74) OFF THE GRID
75) OROWEAT
76) One Mighty Mill, LLC
77) Paskesz Candy Company
78) Pepperidge Farm, Inc.
79) Perfection Bakeries, Inc.
80) Post Consumer Brands, LLC
81) Post Foods, LLC
82) Quaker Bakery Brands, Inc.
83) Raley's
84) Ray's Wholesale Meats
85) Rhodes International Inc.
86) Riviana Foods Inc.
87) Rotella's Italian Bakery Inc.
88) SE GROCERS
89) SHURFINE
90) SPARTAN
91) STATER BROS.
92) SUN HARVEST
93) SUN PUFFS
94) Safeway, Inc.
95) Save Mart Supermarkets Inc.
96) Schmidt Baking Company
97) Schnuck Markets, Inc.
98) Schwebel Baking Company
99) SinfulColors, Inc.
100) Smart & Final Iris Corporation
101) Sourdough:  A European Bakery
102) Stater Bros. Markets Inc.
103) Supervalu, Inc.
104) THAT'S SMART!
105) Target Stores
106) The J.M. Smucker Company
107) The King Arthur Flour Company, Inc.
108) The Kroger Co.
109) The Moran Group Incorporated
110) The Quaker Oats Company
111) Topco Associates, Inc.
112) Tops Markets, LLC
113) Toufayan Bakery Inc
114) Tyson Foods, Inc.
115) Unique Pretzel Bakery
116) United Natural Foods, Inc.
117) V3G International, LLC
118) WEIS QUALITY
119) Wakefern Food Corporation
120) Wal-Mart Stores, Inc.
121) Wasabrod Ab Sweden
122) Weaver Popcorn Company, Inc.
123) Wegmans Food Markets, Inc.
124) Wegmans Food Markets, Inc.
125) Weis Markets, Inc.
126) Western Family Foods, Inc.
127) Winco Foods, Inc.
128) World Variety Produce, Inc.

Which number is your brand?: 120

In [11]:
# creates new dataframe of the brand provided by user
df_selected_brand = df_select_branded_food[df_select_branded_food["brand_owner"] == brand]

df_selected_brand

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
46676,358260,"Wal-Mart Stores, Inc.",NaN,NaN,078742371047,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,NaN,2018-06-28,2019-04-01,United States,NaN,NaN,NaN,NaN
74555,386215,"Wal-Mart Stores, Inc.",NaN,NaN,078742434087,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,NaN,2018-06-28,2019-04-01,United States,NaN,NaN,NaN,NaN
84965,396651,"Wal-Mart Stores, Inc.",NaN,NaN,078742371054,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,NaN,2018-06-28,2019-04-01,United States,NaN,NaN,NaN,NaN
105362,417131,"Wal-Mart Stores, Inc.",NaN,NaN,078742105239,"POPCORN, CANOLA OIL AND/OR SUNFLOWER OIL, SALT...",NaN,30.0,g,3 cup,"Popcorn, Peanuts, Seeds & Related Snacks",LI,NaN,2017-07-14,2019-04-01,United States,NaN,NaN,NaN,NaN
499313,1055689,"Wal-Mart Stores, Inc.",NaN,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,NaN,2020-06-19,2020-07-30,United States,NaN,NaN,NaN,NaN
525720,1856594,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742013718,100% WHOLE GRAIN ROLLED OATS,NaN,40.0,g,NaN,Cereal,LI,18 oz/510 g,2021-02-27,2021-07-29,United States,NaN,NaN,NaN,NaN
531087,1861977,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,18 oz/510 g,2021-02-17,2021-07-29,United States,NaN,NaN,NaN,NaN
580825,1172447,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371047,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,NaN,2018-06-28,2021-02-26,United States,NaN,NaN,NaN,NaN
605672,1197453,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,NaN,2020-07-28,2021-02-26,United States,NaN,NaN,NaN,NaN
614821,1206640,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371054,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,NaN,2018-06-28,2021-02-26,United States,NaN,NaN,NaN,NaN
633509,1225435,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742105239,"POPCORN, CANOLA OIL AND/OR SUNFLOWER OIL, SALT...",NaN,30.0,g,NaN,"Popcorn, Peanuts, Seeds & Related Snacks",LI,NaN,2017-07-14,2021-02-26,United States,NaN,NaN,NaN,NaN
865154,1464467,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371047,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,NaN,2021-02-19,2021-03-19,United States,NaN,NaN,NaN,NaN
878216,1477574,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742013718,100% WHOLE GRAIN ROLLED OATS,NaN,40.0,g,NaN,Cereal,LI,NaN,2021-02-27,2021-03-19,United States,NaN,NaN,NaN,NaN
890023,1489495,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,NaN,2021-02-17,2021-03-19,United States,NaN,NaN,NaN,NaN
899183,1498693,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371054,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,NaN,2021-02-17,2021-03-19,United States,NaN,NaN,NaN,NaN
917877,1517495,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742105239,"POPCORN, CANOLA OIL AND/OR SUNFLOWER OIL, SALT...",NaN,30.0,g,NaN,"Popcorn, Peanuts, Seeds & Related Snacks",LI,NaN,2021-02-17,2021-03-19,United States,NaN,NaN,NaN,NaN
971262,1570962,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,605388927279,DURUM WHOLE GRAIN WHOLE WHEAT FLOUR.,NaN,75.0,g,NaN,Pasta by Shape & Type,LI,NaN,2021-02-26,2021-03-19,United States,NaN,NaN,NaN,NaN
1348667,2008946,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371047,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,42 oz/1.19 kg,2021-02-19,2021-10-28,United States,NaN,NaN,NaN,NaN
1370085,2030423,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371054,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,NaN,Cereal,LI,42 oz/1.19 kg,2021-02-17,2021-10-28,United States,NaN,NaN,NaN,NaN
1414061,2074475,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,605388927279,DURUM WHOLE GRAIN WHOLE WHEAT FLOUR.,NaN,75.0,g,NaN,Pasta by Shape & Type,LI,375 g,2021-02-26,2021-10-28,United States,NaN,NaN,NaN,NaN
1602530,2283324,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,18 oz/510 g,2022-03-28,2022-05-23,United States,NaN,NaN,NaN,NaN
1604760,2285567,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371047,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,42 oz/1.19 kg,2022-03-28,2022-05-23,United States,NaN,NaN,NaN,NaN
1604761,2285568,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371054,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,42 oz/1.19 kg,2022-03-28,2022-05-23,United States,NaN,NaN,NaN,NaN
1641716,2323014,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742371054,100% WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,42 oz/1.19 kg,2021-02-17,2022-06-21,United States,NaN,NaN,NaN,NaN
1644516,2325990,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,18 oz/510 g,2021-02-17,2022-06-21,United States,NaN,NaN,NaN,NaN
1653099,2334853,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,18 oz/510 g,2021-02-17,2022-07-29,United States,NaN,NaN,NaN,NaN
1657880,2339851,"Wal-Mart Stores, Inc.",GREAT VALUE,NaN,078742434087,WHOLE GRAIN ROLLED OATS.,NaN,40.0,g,0.5 cup,Cereal,LI,18 oz/510 g,2021-02-17,2022-09-15,United States,NaN,NaN,NaN,NaN

In [12]:
# get the last row and get the fdc_id of the brand
df_selected_brand = df_selected_brand.iloc[-1]

df_selected_brand

fdc_id                                          2339851
brand_owner                       Wal-Mart Stores, Inc.
brand_name                                  GREAT VALUE
subbrand_name                                       NaN
gtin_upc                                   078742434087
ingredients                    WHOLE GRAIN ROLLED OATS.
not_a_significant_source_of                         NaN
serving_size                                       40.0
serving_size_unit                                     g
household_serving_fulltext                      0.5 cup
branded_food_category                            Cereal
data_source                                          LI
package_weight                              18 oz/510 g
modified_date                                2021-02-17
available_date                               2022-09-15
market_country                            United States
discontinued_date                                   NaN
preparation_state_code                              NaN
trade_channel                                       NaN
short_description                                   NaN
Name: 1657880, dtype: object

In [13]:
fdc_id = df_selected_brand["fdc_id"]

In [14]:
fdc_id

2339851

In [15]:
#list_fdc_ids = df_brand["fdc_id"].tolist()

df_foods = df_food[df_food["fdc_id"] == fdc_id]

df_foods

,fdc_id,data_type,description,food_category_id,publication_date
1657880,2339851,branded_food,"100% WHOLE GRAIN QUICK OATS, 100% WHOLE GRAIN",NaN,2022-09-15

In [16]:
descriptions = df_foods["description"].tolist()

# get unique foods and sort the list
unique_list = []
for x in descriptions:
    if x not in unique_list:
        unique_list.append(x)
unique_list = sorted(unique_list)
        
# print out numbered list of unique foods
for i in range(0, len(unique_list)):
    print(str(i+1) + ") " + unique_list[i])
print()

# ask user which number the food is the correct food
number = int(input("Which number is your food?: "))
food = unique_list[number - 1]

1) 100% WHOLE GRAIN QUICK OATS, 100% WHOLE GRAIN

Which number is your food?: 1

In [17]:
df_foods_unique = df_foods[df_foods["description"] == food]

df_foods_unique

,fdc_id,data_type,description,food_category_id,publication_date
1657880,2339851,branded_food,"100% WHOLE GRAIN QUICK OATS, 100% WHOLE GRAIN",NaN,2022-09-15

In [18]:
df_food = df_foods_unique.iloc[-1]

fdc_id = df_food["fdc_id"]

# Get all the nutrients that are equal to the fdcId
df_food_nutrients_id = df_foods[df_foods["fdc_id"] == fdc_id]

In [19]:
df_food_nutrients_id

,fdc_id,data_type,description,food_category_id,publication_date
1657880,2339851,branded_food,"100% WHOLE GRAIN QUICK OATS, 100% WHOLE GRAIN",NaN,2022-09-15

# Get the Nutrients

In [24]:
df_nutrient = pd.read_csv("food_nutrient.csv")

In [25]:
df_nutrient

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,13706913,1105904,1003,0.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN
1,13706914,1105904,1004,93.33,NaN,71.0,NaN,NaN,NaN,NaN,NaN
2,13706915,1105904,1005,0.00,NaN,75.0,NaN,NaN,NaN,NaN,NaN
3,13706924,1105904,1110,0.00,NaN,75.0,NaN,NaN,NaN,NaN,NaN
4,13706918,1105904,1079,0.00,NaN,75.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
23051001,31220236,2512370,1087,0.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN
23051002,31220233,2512370,1008,857.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN
23051003,31220237,2512370,1089,0.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN
23051004,31220238,2512370,1092,0.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN
23051005,31220239,2512370,1093,0.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN

In [26]:
df_nutrients_id = df_nutrient[df_nutrient["fdc_id"] == fdc_id]

In [28]:
df_nutrient2 = df_nutrients_id[["nutrient_id","amount"]]

In [29]:
df_nutrient2

          nutrient_id  amount
20889668         1089    4.25
20889669         1003   12.50
20889670         1093    0.00
20889671         1084    5.00
20889672         1257    0.00
20889673         1004    6.25
20889674         1253    0.00
20889675         1082    5.00
20889676         1005   67.50
20889677         1079   10.00
20889678         2000    0.00
20889679         1110    0.00
20889680         1293    2.50
20889681         1092  350.00
20889682         1087   50.00
20889683         1258    0.00
20889684         1235    0.00
20889685         1292    2.50
20889686         1008  350.00

In [30]:
df_nutrient = pd.read_csv("nutrient.csv")

In [32]:
nutrient_ids = df_nutrient2["nutrient_id"].tolist()

In [36]:
nutrient_ids

[1089,
 1003,
 1093,
 1084,
 1257,
 1004,
 1253,
 1082,
 1005,
 1079,
 2000,
 1110,
 1293,
 1092,
 1087,
 1258,
 1235,
 1292,
 1008]

In [43]:
df_nutrients = df_nutrient[df_nutrient["id"].isin(nutrient_ids)]

df_nutrients

       id                                      name unit_name
4    1003                                   Protein         G
5    1004                         Total lipid (fat)         G
6    1005               Carbohydrate, by difference         G
9    1008                                    Energy      KCAL
80   1079                      Fiber, total dietary         G
83   1082                            Fiber, soluble         G
85   1084                          Fiber, insoluble         G
88   1087                               Calcium, Ca        MG
90   1089                                  Iron, Fe        MG
93   1092                              Potassium, K        MG
94   1093                                Sodium, Na        MG
111  1110  Vitamin D (D2 + D3), International Units        IU
236  1235                             Sugars, added         G
254  1253                               Cholesterol        MG
258  1257                  Fatty acids, total trans         G
259  1258              Fatty acids, total saturated         G
292  1292        Fatty acids, total monounsaturated         G
293  1293        Fatty acids, total polyunsaturated         G
415  2000              Sugars, total including NLEA         G

In [44]:
dfmain = df_nutrients.merge(df_nutrient2, left_on=['id'], right_on=['nutrient_id'], how = 'outer')

In [45]:
dfmain

,id,name,unit_name,nutrient_id,amount
0,1003,Protein,G,1003,12.50
1,1004,Total lipid (fat),G,1004,6.25
2,1005,"Carbohydrate, by difference",G,1005,67.50
3,1008,Energy,KCAL,1008,350.00
4,1079,"Fiber, total dietary",G,1079,10.00
5,1082,"Fiber, soluble",G,1082,5.00
6,1084,"Fiber, insoluble",G,1084,5.00
7,1087,"Calcium, Ca",MG,1087,50.00
8,1089,"Iron, Fe",MG,1089,4.25
9,1092,"Potassium, K",MG,1092,350.00
10,1093,"Sodium, Na",MG,1093,0.00
11,1110,"Vitamin D (D2 + D3), International Units",IU,1110,0.00
12,1235,"Sugars, added",G,1235,0.00
13,1253,Cholesterol,MG,1253,0.00
14,1257,"Fatty acids, total trans",G,1257,0.00
15,1258,"Fatty acids, total saturated",G,1258,0.00
16,1292,"Fatty acids, total monounsaturated",G,1292,2.50
17,1293,"Fatty acids, total polyunsaturated",G,1293,2.50
18,2000,"Sugars, total including NLEA",G,2000,0.00

In [46]:
dfmain = dfmain.drop(columns=["nutrient_id"])
dfmain

      id                                      name unit_name  amount
0   1003                                   Protein         G   12.50
1   1004                         Total lipid (fat)         G    6.25
2   1005               Carbohydrate, by difference         G   67.50
3   1008                                    Energy      KCAL  350.00
4   1079                      Fiber, total dietary         G   10.00
5   1082                            Fiber, soluble         G    5.00
6   1084                          Fiber, insoluble         G    5.00
7   1087                               Calcium, Ca        MG   50.00
8   1089                                  Iron, Fe        MG    4.25
9   1092                              Potassium, K        MG  350.00
10  1093                                Sodium, Na        MG    0.00
11  1110  Vitamin D (D2 + D3), International Units        IU    0.00
12  1235                             Sugars, added         G    0.00
13  1253                               Cholesterol        MG    0.00
14  1257                  Fatty acids, total trans         G    0.00
15  1258              Fatty acids, total saturated         G    0.00
16  1292        Fatty acids, total monounsaturated         G    2.50
17  1293        Fatty acids, total polyunsaturated         G    2.50
18  2000              Sugars, total including NLEA         G    0.00

In [47]:
list_nutrient_names = dfmain["name"].tolist()
list_nutrient_units = dfmain["unit_name"].tolist()
list_nutrient_amounts = dfmain["amount"].tolist()

In [56]:
df_selected_brand

fdc_id                                          2339851
brand_owner                       Wal-Mart Stores, Inc.
brand_name                                  GREAT VALUE
subbrand_name                                       NaN
gtin_upc                                   078742434087
ingredients                    WHOLE GRAIN ROLLED OATS.
not_a_significant_source_of                         NaN
serving_size                                       40.0
serving_size_unit                                     g
household_serving_fulltext                      0.5 cup
branded_food_category                            Cereal
data_source                                          LI
package_weight                              18 oz/510 g
modified_date                                2021-02-17
available_date                               2022-09-15
market_country                            United States
discontinued_date                                   NaN
preparation_state_code                              NaN
trade_channel                                       NaN
short_description                                   NaN
Name: 1657880, dtype: object

In [57]:
serving_size = df_selected_brand["serving_size"].tolist()

In [58]:
serving_size

40.0

In [60]:
serving_size_unit = df_selected_brand["serving_size_unit"]

In [61]:
serving_size_unit

'g'

In [63]:
household_serving = df_selected_brand["household_serving_fulltext"]

In [64]:
household_serving

'0.5 cup'

In [65]:
print("Serving size is " + str(serving_size) + serving_size_unit)
print("equivalent to " + household_serving)
servings = input("How many servings did you consume? ")

# convert 100 grams to 1 serving
# Serving size is 40 grams. Nutrients used 100 grams, so first multiply serving size by servings consumed.
serving_size_consumed = serving_size * float(servings)
serving_size_nutrients = 100
serving_size_nutrients_consumed = serving_size_nutrients / serving_size_consumed

for i in range(0, len(list_nutrient_amounts)):
    list_nutrient_amounts[i] /= serving_size_nutrients_consumed

print()
for i in range(0, len(list_nutrient_names)):
    print(list_nutrient_names[i])
    print(str(list_nutrient_amounts[i]) + " " + str(list_nutrient_units[i]))

Serving size is 40.0g
equivalent to 0.5 cup
How many servings did you consume? 1

Protein
5.0 G
Total lipid (fat)
2.5 G
Carbohydrate, by difference
27.0 G
Energy
140.0 KCAL
Fiber, total dietary
4.0 G
Fiber, soluble
2.0 G
Fiber, insoluble
2.0 G
Calcium, Ca
20.0 MG
Iron, Fe
1.7 MG
Potassium, K
140.0 MG
Sodium, Na
0.0 MG
Vitamin D (D2 + D3), International Units
0.0 IU
Sugars, added
0.0 G
Cholesterol
0.0 MG
Fatty acids, total trans
0.0 G
Fatty acids, total saturated
0.0 G
Fatty acids, total monounsaturated
1.0 G
Fatty acids, total polyunsaturated
1.0 G
Sugars, total including NLEA
0.0 G

# Get Ingredients

In [152]:
ingredients = df_brands["ingredients"].tolist()

In [153]:
print("Ingredients: ")
print(ingredients[0])

Ingredients:
100% WHOLE GRAIN ROLLED OATS.

# Create Dataframes